run:
  timeout: 5m
linters:
  disable-all: true
  enable:
    - gofmt
    - govet
    - bodyclose
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - nakedret
    - rowserrcheck
    - unconvert
    - unparam
    - unused
    - errorlint
    - gocritic
    - goimports
    - gosec
linters-settings:
  gofmt:
    rewrite-rules:
      - pattern: interface{}
        replacement: any
